# Tachiyomi (RIP king!) issue template

name: 🐞 Issue report
description: Report an issue
labels: [ bug ]
body:

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: textarea
    id: crash-logs
    attributes:
      label: Crash logs (or stack trace)
      placeholder: |
        You can paste the crash logs in plain text or upload it as an attachment.

  - type: input
    id: flixclusive-version
    attributes:
      label: App version
      description: You can find the app's version in **Preferences → About**.
      placeholder: |
        Example: "1.2.1"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 11"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: List your device and model.
      placeholder: |
        Example: "Google Pixel 5"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Please read carefully! Reading comprehension is rare nowadays.
      options:
        - label: I am ***fully confident*** that this issue is related solely to the app and not to any provider.
          required: true
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to the **[pre-release version](https://github.com/flixclusiveorg/Flixclusive/releases/tag/pre-release)**.
          required: true
