name: Pre-release CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: "pre-release"
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Build release and prerelease
        uses: gradle/gradle-command-action@v2
        with:
          arguments: :app:assembleRelease :app:assemblePrerelease

      - name: Sign release APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign pre-release APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/prerelease
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        run: |
          set -e
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk flixclusive-release.apk
          sha=`sha256sum flixclusive-release.apk | awk '{ print $1 }'`
          echo "RELEASE_SHA=$sha" >> $GITHUB_ENV
          
          mv app/build/outputs/apk/prerelease/app-prerelease-unsigned-signed.apk flixclusive-prerelease.apk
          sha=`sha256sum flixclusive-prerelease.apk | awk '{ print $1 }'`
          echo "PRERELEASE_SHA=$sha" >> $GITHUB_ENV
          

      - name: Create Pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "pre-release"
          name: "Pre-release build"
          body: |
            ---
            _NOTE: Android TV is incomplete. Though, you could test it now._
            
            ### Changes
            
            ---
            ##### The `prerelease` apk is similar to release but for _debugging_ purposes only. Use this if you want to test the latest features without messing up your authentic release data.
            ---
            
            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | release | ${{ env.RELEASE_SHA }} |
            | pre-release | ${{ env.PRERELEASE_SHA }} |
          files: |
            flixclusive-release.apk
            flixclusive-prerelease.apk
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
